import { createGlobalTheme } from '@vanilla-extract/css';

import { contract } from './contract.css';

import { fonts } from './fonts';

import { space } from './space';

import { ROOT_SELECTOR, THEME_MODE_ATTRIBUTE } from '../constants';

import {
  slateDark,
  slateDarkA,
  amberDark,
  blueDark,
  redDark,
  greenDark,
  purpleDark,
  yellowDark,
  orangeDark,
} from '@radix-ui/colors';

export const dark = {
  color: {
    neutral: {
      1: slateDark.slate1,
      2: slateDark.slate2,
      3: slateDark.slate3,
      4: slateDark.slate4,
      5: slateDark.slate5,
      6: slateDark.slate6,
      7: slateDark.slate7,
      8: slateDark.slate8,
      9: slateDark.slate9,
      10: slateDark.slate10,
      11: slateDark.slate11,
      12: slateDark.slate12,
    },
    neutralAlpha: {
      1: slateDarkA.slateA1,
      2: slateDarkA.slateA2,
      3: slateDarkA.slateA3,
      4: slateDarkA.slateA4,
      5: slateDarkA.slateA5,
      6: slateDarkA.slateA6,
      7: slateDarkA.slateA7,
      8: slateDarkA.slateA8,
      9: slateDarkA.slateA9,
      10: slateDarkA.slateA10,
      11: slateDarkA.slateA11,
      12: slateDarkA.slateA12,
    },
    amber: {
      1: amberDark.amber1,
      2: amberDark.amber2,
      3: amberDark.amber3,
      4: amberDark.amber4,
      5: amberDark.amber5,
      6: amberDark.amber6,
      7: amberDark.amber7,
      8: amberDark.amber8,
      9: amberDark.amber9,
      10: amberDark.amber10,
      11: amberDark.amber11,
      12: amberDark.amber12,
    },
    yellow: {
      1: yellowDark.yellow1,
      2: yellowDark.yellow2,
      3: yellowDark.yellow3,
      4: yellowDark.yellow4,
      5: yellowDark.yellow5,
      6: yellowDark.yellow6,
      7: yellowDark.yellow7,
      8: yellowDark.yellow8,
      9: yellowDark.yellow9,
      10: yellowDark.yellow10,
      11: yellowDark.yellow11,
      12: yellowDark.yellow12,
    },
    red: {
      1: redDark.red1,
      2: redDark.red2,
      3: redDark.red3,
      4: redDark.red4,
      5: redDark.red5,
      6: redDark.red6,
      7: redDark.red7,
      8: redDark.red8,
      9: redDark.red9,
      10: redDark.red10,
      11: redDark.red11,
      12: redDark.red12,
    },
    orange: {
      1: orangeDark.orange1,
      2: orangeDark.orange2,
      3: orangeDark.orange3,
      4: orangeDark.orange4,
      5: orangeDark.orange5,
      6: orangeDark.orange6,
      7: orangeDark.orange7,
      8: orangeDark.orange8,
      9: orangeDark.orange9,
      10: orangeDark.orange10,
      11: orangeDark.orange11,
      12: orangeDark.orange12,
    },
    blue: {
      1: blueDark.blue1,
      2: blueDark.blue2,
      3: blueDark.blue3,
      4: blueDark.blue4,
      5: blueDark.blue5,
      6: blueDark.blue6,
      7: blueDark.blue7,
      8: blueDark.blue8,
      9: blueDark.blue9,
      10: blueDark.blue10,
      11: blueDark.blue11,
      12: blueDark.blue12,
    },
    green: {
      1: greenDark.green1,
      2: greenDark.green2,
      3: greenDark.green3,
      4: greenDark.green4,
      5: greenDark.green5,
      6: greenDark.green6,
      7: greenDark.green7,
      8: greenDark.green8,
      9: greenDark.green9,
      10: greenDark.green10,
      11: greenDark.green11,
      12: greenDark.green12,
    },
    purple: {
      1: purpleDark.purple1,
      2: purpleDark.purple2,
      3: purpleDark.purple3,
      4: purpleDark.purple4,
      5: purpleDark.purple5,
      6: purpleDark.purple6,
      7: purpleDark.purple7,
      8: purpleDark.purple8,
      9: purpleDark.purple9,
      10: purpleDark.purple10,
      11: purpleDark.purple11,
      12: purpleDark.purple12,
    },
  },
  fonts,
  space,
};

export const darkColors = createGlobalTheme(
  `${ROOT_SELECTOR}[${THEME_MODE_ATTRIBUTE}='dark']`,
  contract,
  dark,
);
