import { createGlobalTheme } from '@vanilla-extract/css';

import { contract } from './contract.css';

import { fonts } from './fonts';

import { space } from './space';

import { ROOT_SELECTOR, THEME_MODE_ATTRIBUTE } from '../constants';
import {
  amber,
  gray,
  grayA,
  yellow,
  red,
  orange,
  blue,
  green,
  purple,
} from '@radix-ui/colors';

export const light = {
  color: {
    neutral: {
      1: gray.gray1,
      2: gray.gray2,
      3: gray.gray3,
      4: gray.gray4,
      5: gray.gray5,
      6: gray.gray6,
      7: gray.gray7,
      8: gray.gray8,
      9: gray.gray9,
      10: gray.gray10,
      11: gray.gray11,
      12: gray.gray12,
    },
    neutralAlpha: {
      1: grayA.grayA1,
      2: grayA.grayA2,
      3: grayA.grayA3,
      4: grayA.grayA4,
      5: grayA.grayA5,
      6: grayA.grayA6,
      7: grayA.grayA7,
      8: grayA.grayA8,
      9: grayA.grayA9,
      10: grayA.grayA10,
      11: grayA.grayA11,
      12: grayA.grayA12,
    },
    amber: {
      1: amber.amber1,
      2: amber.amber2,
      3: amber.amber3,
      4: amber.amber4,
      5: amber.amber5,
      6: amber.amber6,
      7: amber.amber7,
      8: amber.amber8,
      9: amber.amber9,
      10: amber.amber10,
      11: amber.amber11,
      12: amber.amber12,
    },
    yellow: {
      1: yellow.yellow1,
      2: yellow.yellow2,
      3: yellow.yellow3,
      4: yellow.yellow4,
      5: yellow.yellow5,
      6: yellow.yellow6,
      7: yellow.yellow7,
      8: yellow.yellow8,
      9: yellow.yellow9,
      10: yellow.yellow10,
      11: yellow.yellow11,
      12: yellow.yellow12,
    },
    red: {
      1: red.red1,
      2: red.red2,
      3: red.red3,
      4: red.red4,
      5: red.red5,
      6: red.red6,
      7: red.red7,
      8: red.red8,
      9: red.red9,
      10: red.red10,
      11: red.red11,
      12: red.red12,
    },
    orange: {
      1: orange.orange1,
      2: orange.orange2,
      3: orange.orange3,
      4: orange.orange4,
      5: orange.orange5,
      6: orange.orange6,
      7: orange.orange7,
      8: orange.orange8,
      9: orange.orange9,
      10: orange.orange10,
      11: orange.orange11,
      12: orange.orange12,
    },
    blue: {
      1: blue.blue1,
      2: blue.blue2,
      3: blue.blue3,
      4: blue.blue4,
      5: blue.blue5,
      6: blue.blue6,
      7: blue.blue7,
      8: blue.blue8,
      9: blue.blue9,
      10: blue.blue10,
      11: blue.blue11,
      12: blue.blue12,
    },
    green: {
      1: green.green1,
      2: green.green2,
      3: green.green3,
      4: green.green4,
      5: green.green5,
      6: green.green6,
      7: green.green7,
      8: green.green8,
      9: green.green9,
      10: green.green10,
      11: green.green11,
      12: green.green12,
    },
    purple: {
      1: purple.purple1,
      2: purple.purple2,
      3: purple.purple3,
      4: purple.purple4,
      5: purple.purple5,
      6: purple.purple6,
      7: purple.purple7,
      8: purple.purple8,
      9: purple.purple9,
      10: purple.purple10,
      11: purple.purple11,
      12: purple.purple12,
    },
  },
  fonts,
  space,
};

export const lightColors = createGlobalTheme(
  `${ROOT_SELECTOR}[${THEME_MODE_ATTRIBUTE}='light']`,
  contract,
  light,
);
