name: Types Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  types_check:
    name: Types Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install  

      - name: Do types check
        run: pnpm types

